export enum MimeType {
  threegp = 'video/3gpp',
  apk = 'application/vnd.android.package-archive',
  asf = 'video/x-ms-asf',
  avi = 'video/x-msvideo',
  bin = 'application/octet-stream',
  bmp = 'image/bmp',
  c = 'text/plain',
  // eslint-disable-next-line @typescript-eslint/no-duplicate-enum-values
  class_ = 'application/octet-stream',
  // eslint-disable-next-line @typescript-eslint/no-duplicate-enum-values
  conf = 'text/plain',
  // eslint-disable-next-line @typescript-eslint/no-duplicate-enum-values
  cpp = 'text/plain',
  doc = 'application/msword',
  docx = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  xls = 'application/vnd.ms-excel',
  xlsx = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  // eslint-disable-next-line @typescript-eslint/no-duplicate-enum-values
  exe = 'application/octet-stream',
  gif = 'image/gif',
  gtar = 'application/x-gtar',
  gz = 'application/x-gzip',
  // eslint-disable-next-line @typescript-eslint/no-duplicate-enum-values
  h = 'text/plain',

  htm = 'text/html',
  // eslint-disable-next-line @typescript-eslint/no-duplicate-enum-values
  html = 'text/html',
  jar = 'application/java-archive',
  // eslint-disable-next-line @typescript-eslint/no-duplicate-enum-values
  java = 'text/plain',
  jpeg = 'image/jpeg',
  // eslint-disable-next-line @typescript-eslint/no-duplicate-enum-values
  jpg = 'image/jpeg',
  js = 'application/x-javascript',
  // eslint-disable-next-line @typescript-eslint/no-duplicate-enum-values
  log = 'text/plain',
  m3u = 'audio/x-mpegurl',
  m4a = 'audio/mp4a-latm',
  // eslint-disable-next-line @typescript-eslint/no-duplicate-enum-values
  m4b = 'audio/mp4a-latm',
  // eslint-disable-next-line @typescript-eslint/no-duplicate-enum-values
  m4p = 'audio/mp4a-latm',
  m4u = 'video/vnd.mpegurl',
  m4v = 'video/x-m4v',
  mov = 'video/quicktime',
  mp2 = 'audio/x-mpeg',
  // eslint-disable-next-line @typescript-eslint/no-duplicate-enum-values
  mp3 = 'audio/x-mpeg',
  mp4 = 'video/mp4',
  mpc = 'application/vnd.mpohun.certificate',
  mpe = 'video/mpeg',
  // eslint-disable-next-line @typescript-eslint/no-duplicate-enum-values
  mpeg = 'video/mpeg',
  // eslint-disable-next-line @typescript-eslint/no-duplicate-enum-values
  mpg = 'video/mpeg',
  // eslint-disable-next-line @typescript-eslint/no-duplicate-enum-values
  mpg4 = 'video/mp4',
  mpga = 'audio/mpeg',
  msg = 'application/vnd.ms-outlook',
  ogg = 'audio/ogg',
  pdf = 'application/pdf',
  png = 'image/png',
  pps = 'application/vnd.ms-powerpoint',
  // eslint-disable-next-line @typescript-eslint/no-duplicate-enum-values
  ppt = 'application/vnd.ms-powerpoint',
  pptx = 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  // eslint-disable-next-line @typescript-eslint/no-duplicate-enum-values
  prop = 'text/plain',
  // eslint-disable-next-line @typescript-eslint/no-duplicate-enum-values
  rc = 'text/plain',
  rmvb = 'audio/x-pn-realaudio',
  rtf = 'application/rtf',
  // eslint-disable-next-line @typescript-eslint/no-duplicate-enum-values
  sh = 'text/plain',
  tar = 'application/x-tar',
  tgz = 'application/x-compressed',
  // eslint-disable-next-line @typescript-eslint/no-duplicate-enum-values
  txt = 'text/plain',
  wav = 'audio/x-wav',
  wma = 'audio/x-ms-wma',
  wmv = 'audio/x-ms-wmv',
  wps = 'application/vnd.ms-works',
  // eslint-disable-next-line @typescript-eslint/no-duplicate-enum-values
  xml = 'text/plain',
  z = 'application/x-compress',
  zip = 'application/x-zip-compressed',
}
